# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'RxSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # RxSwift全家桶
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxRealm'
    pod 'RxRealmDataSources'
    pod 'RxKeyboard'
    
    # 网络请求及解析
    pod 'Moya/RxSwift', '~> 11.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire'
    pod 'ObjectMapper'
    
    # 文件管理
    pod 'R.swift'
    
    # UI布局
    pod 'SnapKit', '~> 4.0.0'
  # Pods for RxSwiftDemo

  target 'RxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
